### ISSUE TITLE
non-working bullshit

### ISSUE THREAD

**Issue by T-8000N71** [barry-far/V2ray-Configs#84]
it is impossible to start the kernel - not a single config is working. my requests are ignored. You're finished.

**Comment by barry-far** [comment]
Hey @T-8000N71  ,
Chill bro. email me at arta.shahin.01@gmail.com

**Comment by T-8000N71** [comment]
> Hey @T-8000N71 , Chill bro. email me at [arta.shahin.01@gmail.com](mailto:arta.shahin.01@gmail.com)

I don't feel like talking to you. these configs do not work in any program. neither v2rayn nor nekoray. I wrote about the error. if the error persists, then you don't care. and since you don't care, I'm not interested anymore. 
earlier, I provided comprehensive information about the problem both here and to the v2rayn developers themselves. Nobody cares.
If no one cares? - why shouldn't I care? it doesn't matter. I've said it all.

**Comment by barry-far** [comment]
> > Hey @T-8000N71 , Chill bro. email me at [arta.shahin.01@gmail.com](mailto:arta.shahin.01@gmail.com)
> 
> I don't feel like talking to you. these configs do not work in any program. neither v2rayn nor nekoray. I wrote about the error. if the error persists, then you don't care. and since you don't care, I'm not interested anymore. earlier, I provided comprehensive information about the problem both here and to the v2rayn developers themselves. Nobody cares. If no one cares? - why shouldn't I care? it doesn't matter. I've said it all.

Calm down.
The problem is not from sublinks so the main problem is from their xray core which can't handle this huge amount of configs. I told you to use Hiddify application instead of these outdated apps to get connected.

If you read the readme carefully you will find out the help!


Here is the latest version with some instructions : 
https://github.com/hiddify/Hiddify-Manager/wiki/Tutorial-for-HiddifyNext-app#adding-a-profile-to-the-app


If the problem exists with Hiddify, please share me a screenshot🫂

**Comment by T-8000N71** [comment]
this app is even worse. it doesn't show the speed. it shows the delay. but it does not show the speed. why do I need 4000 servers with low speed?I wrote to the developers of v2rayn, they write that these are configs with errors. But I don't really care. I can see that the developers of v2rayn that you don't care.
you write disgusting software and make a lot of mistakes. that is why humanity will destroy Skynet. there is sloppiness and sloppiness all around. I found another way.
